### ISSUE TITLE
Own image and Audio

### ISSUE THREAD

**Issue by romioos222** [PhurinutR/MakeItTalk_Demo#1]
Hello thanks for the good tutorial.
is there a way to get own image and audio in the Gui
or is this for further develop

**Comment by PhurinutR** [comment]
Hi Ramon Esperanza! I am so glad that this tutorial can be useful for others. According to your question, in order to use your own image or audio you could change or add the path of the prefered audio or the image to the `audio_paths` or `image_paths`, respectively, in the **GUI.py** file. By doing this, you can add any picture you like to the GUI and the program will help you pass the selected paths to the inferencing process after clicking **"Make It Talk!!"** button.

**Comment by PhurinutR** [comment]
Hi Ramon Esperanza! I am so glad that this tutorial can be useful for others. According to your question, in order to use your own image or audio you could change or add the path of the prefered audio or the image to the `audio_paths` or `image_paths`, respectively, in the **GUI.py** file. By doing this, you can add any picture you like to the GUI and the program will help you pass the selected paths to the inferencing process after clicking **"Make It Talk!!"** button.

**Comment by romioos222** [comment]
Oke thank you su much. this realy helps

**Comment by romioos222** [comment]
Oke thank you su much. this realy helps
